version: '3.8'

services:

  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./src/task:/var/www/task
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - task

  task:
    build:
      context: ./src/task
    working_dir: /var/www/task
    volumes:
      - ./src/task:/var/www/task
